import React from "react";
import Twemoji from "react-twemoji";

const TwemojiFlag = ({ countryCode, className = "", style = {} }) => {
  // Get the flag emoji from the country code
  const getFlagEmoji = (code) => {
    const countryFlags = {
      AF: "🇦🇫",
      AL: "🇦🇱",
      DZ: "🇩🇿",
      AS: "🇦🇸",
      AO: "🇦🇴",
      AG: "🇦🇬",
      AR: "🇦🇷",
      AM: "🇦🇲",
      AW: "🇦🇼",
      AU: "🇦🇺",
      AT: "🇦🇹",
      BH: "🇧🇭",
      BD: "🇧🇩",
      BB: "🇧🇧",
      BE: "🇧🇪",
      BJ: "🇧🇯",
      BA: "🇧🇦",
      BR: "🇧🇷",
      BN: "🇧🇳",
      BG: "🇧🇬",
      BF: "🇧🇫",
      BI: "🇧🇮",
      KH: "🇰🇭",
      CM: "🇨🇲",
      CA: "🇨🇦",
      CV: "🇨🇻",
      CF: "🇨🇫",
      TD: "🇹🇩",
      CL: "🇨🇱",
      CN: "🇨🇳",
      CO: "🇨🇴",
      KM: "🇰🇲",
      CG: "🇨🇬",
      CK: "🇨🇰",
      CR: "🇨🇷",
      CI: "🇨🇮",
      HR: "🇭🇷",
      CU: "🇨🇺",
      CW: "🇨🇼",
      CY: "🇨🇾",
      CZ: "🇨🇿",
      CD: "🇨🇩",
      DK: "🇩🇰",
      DJ: "🇩🇯",
      DM: "🇩🇲",
      DO: "🇩🇴",
      TL: "🇹🇱",
      EC: "🇪🇨",
      EG: "🇪🇬",
      SV: "🇸🇻",
      GQ: "🇬🇶",
      EE: "🇪🇪",
      ET: "🇪🇹",
      FJ: "🇫🇯",
      FI: "🇫🇮",
      FR: "🇫🇷",
      GA: "🇬🇦",
      GM: "🇬🇲",
      GE: "🇬🇪",
      DE: "🇩🇪",
      GH: "🇬🇭",
      GR: "🇬🇷",
      GD: "🇬🇩",
      GP: "🇬🇵",
      GT: "🇬🇹",
      GN: "🇬🇳",
      GW: "🇬🇼",
      GY: "🇬🇾",
      HT: "🇭🇹",
      HN: "🇭🇳",
      HK: "🇭🇰",
      IN: "🇮🇳",
      IR: "🇮🇷",
      IQ: "🇮🇶",
      IE: "🇮🇪",
      IL: "🇮🇱",
      IT: "🇮🇹",
      JM: "🇯🇲",
      JP: "🇯🇵",
      JO: "🇯🇴",
      KZ: "🇰🇿",
      KE: "🇰🇪",
      KI: "🇰🇮",
      KR: "🇰🇷",
      KW: "🇰🇼",
      KG: "🇰🇬",
      LV: "🇱🇻",
      LB: "🇱🇧",
      LR: "🇱🇷",
      LY: "🇱🇾",
      LT: "🇱🇹",
      MO: "🇲🇴",
      MG: "🇲🇬",
      MY: "🇲🇾",
      MV: "🇲🇻",
      ML: "🇲🇱",
      MT: "🇲🇹",
      MH: "🇲🇭",
      MR: "🇲🇷",
      MU: "🇲🇺",
      YT: "🇾🇹",
      MX: "🇲🇽",
      FM: "🇫🇲",
      MN: "🇲🇳",
      ME: "🇲🇪",
      MA: "🇲🇦",
      MZ: "🇲🇿",
      MM: "🇲🇲",
      NA: "🇳🇦",
      NR: "🇳🇷",
      NP: "🇳🇵",
      NL: "🇳🇱",
      NC: "🇳🇨",
      NZ: "🇳🇿",
      NI: "🇳🇮",
      NE: "🇳🇪",
      NG: "🇳🇬",
      MP: "🇲🇵",
      NO: "🇳🇴",
      OM: "🇴🇲",
      PK: "🇵🇰",
      PW: "🇵🇼",
      PA: "🇵🇦",
      PG: "🇵🇬",
      PY: "🇵🇾",
      PE: "🇵🇪",
      PH: "🇵🇭",
      PL: "🇵🇱",
      PT: "🇵🇹",
      PR: "🇵🇷",
      QA: "🇶🇦",
      RE: "🇷🇪",
      RO: "🇷🇴",
      RU: "🇷🇺",
      RW: "🇷🇼",
      LC: "🇱🇨",
      VC: "🇻🇨",
      WS: "🇼🇸",
      ST: "🇸🇹",
      SA: "🇸🇦",
      SN: "🇸🇳",
      RS: "🇷🇸",
      SC: "🇸🇨",
      SL: "🇸🇱",
      SG: "🇸🇬",
      SK: "🇸🇰",
      SI: "🇸🇮",
      SB: "🇸🇧",
      SO: "🇸🇴",
      ZA: "🇿🇦",
      SS: "🇸🇸",
      ES: "🇪🇸",
      LK: "🇱🇰",
      SD: "🇸🇩",
      SR: "🇸🇷",
      SE: "🇸🇪",
      CH: "🇨🇭",
      SY: "🇸🇾",
      TW: "🇹🇼",
      TZ: "🇹🇿",
      TH: "🇹🇭",
      TG: "🇹🇬",
      TO: "🇹🇴",
      TT: "🇹🇹",
      TN: "🇹🇳",
      TR: "🇹🇷",
      TM: "🇹🇲",
      TV: "🇹🇻",
      UG: "🇺🇬",
      UA: "🇺🇦",
      AE: "🇦🇪",
      GB: "🇬🇧",
      US: "🇺🇸",
      UY: "🇺🇾",
      VU: "🇻🇺",
      VE: "🇻🇪",
      VN: "🇻🇳",
      VG: "🇻🇬",
      YE: "🇾🇪",
      ZM: "🇿🇲",
      ID: "🇮🇩",
    };
    return countryFlags[code] || "🏳️";
  };

  const flagEmoji = getFlagEmoji(countryCode);

  return (
    <Twemoji options={{ folder: "svg", ext: ".svg" }}>
      <span className={className} style={style}>
        {flagEmoji}
      </span>
    </Twemoji>
  );
};

export default TwemojiFlag;
